Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,56 +59,56 @@ jobs:
       - id: var
         name: Download
         run: |
-          echo "Download"
-          if [[ ! -z "${{ github.event.inputs.filename }}" ]]; then
-              NAME="${{ github.event.inputs.filename }}"
-              if [[ ! -z "$(echo ${NAME} | grep ".zip")" ]]; then
-                  echo "::set-output name=filename::${NAME%.*}"
-                  echo "${{ github.event.inputs.filename }}"
-                  filename="${NAME%.*}"
-              else
-                  echo "::set-output name=filename::${{ github.event.inputs.filename }}"
-                  echo "Null value"
-                  filename="${{ github.event.inputs.filename }}"
-              fi
-              echo "filename: $filename"
-              if [[ "${{ github.event.inputs.mode }}" == 'wget' ]]; then
-                  wget ${{ github.event.inputs.filelink }} -O "${filename}.zip"
-              elif [[ "${{ github.event.inputs.mode }}" == 'aria2c' ]]; then
-                  aria2c -x16 -j$(nproc) ${{ github.event.inputs.filelink }} -o "${filename}.zip"             
-              elif [[ "${{ github.event.inputs.mode }}" == 'curl' ]]; then
-                  curl -L ${{ github.event.inputs.filelink }} -o "${filename}.zip"
-              elif [[ "${{ github.event.inputs.mode }}" == 'axel' ]]; then
-                  axel -n 16 ${{ github.event.inputs.filelink }} -o "${filename}.zip"
-              fi             
-          else
-              if [[ "${{ github.event.inputs.mode }}" == 'wget' ]]; then
-                  wget --content-disposition -c ${{ github.event.inputs.filelink }}
-              elif [[ "${{ github.event.inputs.mode }}" == 'aria2c' ]]; then
-                  aria2c -x16 -j$(nproc) ${{ github.event.inputs.filelink }}             
-              elif [[ "${{ github.event.inputs.mode }}" == 'curl' ]]; then
-                  curl -OL ${{ github.event.inputs.filelink }}
-              elif [[ "${{ github.event.inputs.mode }}" == 'axel' ]]; then
-                  axel -n 16 ${{ github.event.inputs.filelink }}
-              fi
-              NAME="$(ls -lS *.zip | head -1 | awk '{print $9}')"
-              if [ ! -z "$NAME" ]; then
-                  filename=${NAME%.*}
-              else
-                  tmp="$(find . -maxdepth 1 -type f -size +500M)"
-                  if [ ! -z "$tmp" ]; then
-                      ls -al
-                      echo "Rename"
-                      filename=$(echo $tmp | sed 's#./##')
-                      mv $filename ${filename}.zip
-                  else
-                      echo "Download error"
-                      exit 1
-                  fi
-              fi              
-              echo "::set-output name=filename::$filename"
-          fi
-          ls -al
+         echo "Download"
+         if [[ ! -z "${{ github.event.inputs.filename }}" ]]; then
+         NAME="${{ github.event.inputs.filename }}"
+         if [[ ! -z "$(echo ${NAME} | grep ".zip")" ]]; then
+            echo "::set-output name=filename::${NAME%.*}"
+            echo "${{ github.event.inputs.filename }}"
+            filename="${NAME%.*}"
+         else
+            echo "::set-output name=filename::${{ github.event.inputs.filename }}"
+            echo "Null value"
+            filename="${{ github.event.inputs.filename }}"
+         fi
+         echo "filename: $filename"
+         if [[ "${{ github.event.inputs.mode }}" == 'wget' ]]; then
+            wget ${{ github.event.inputs.filelink }} -O "${filename}.zip"
+         elif [[ "${{ github.event.inputs.mode }}" == 'aria2c' ]]; then
+            aria2c -x16 -j$(nproc) ${{ github.event.inputs.filelink }} -o "${filename}.zip"             
+         elif [[ "${{ github.event.inputs.mode }}" == 'curl' ]]; then
+            curl -L ${{ github.event.inputs.filelink }} -o "${filename}.zip"
+         elif [[ "${{ github.event.inputs.mode }}" == 'axel' ]]; then
+            axel -n 16 ${{ github.event.inputs.filelink }} -o "${filename}.zip"
+         fi             
+         else
+         if [[ "${{ github.event.inputs.mode }}" == 'wget' ]]; then
+            wget --content-disposition -c ${{ github.event.inputs.filelink }}
+         elif [[ "${{ github.event.inputs.mode }}" == 'aria2c' ]]; then
+            aria2c -x16 -j$(nproc) ${{ github.event.inputs.filelink }}             
+         elif [[ "${{ github.event.inputs.mode }}" == 'curl' ]]; then
+            curl -OL ${{ github.event.inputs.filelink }}
+         elif [[ "${{ github.event.inputs.mode }}" == 'axel' ]]; then
+            axel -n 16 ${{ github.event.inputs.filelink }}
+         fi
+         NAME=$(ls -lS *.zip | head -1 | awk '{print $9}')
+         if [ ! -z "$NAME" ]; then
+            filename=${NAME%.*}
+         else
+            tmp=$(find . -maxdepth 1 -type f -size +500M)
+            if [ ! -z "$tmp" ]; then
+                ls -al
+                echo "Rename"
+                filename=$(echo $tmp | sed 's#./##')
+                mv $filename ${filename}.zip
+            else
+                echo "Download error"
+                exit 1
+            fi
+         fi              
+         echo "::set-output name=filename::$filename"
+         fi
+         ls -al
 
       - name: Payload Extractor
         run: |
